language: csharp
sudo: required
os: linux
dist: trusty
addons:
  apt:
    packages:
    - libunwind8
    - gettext
    - libssl-dev
    - libcurl4-openssl-dev
    - zlib1g
    - libicu-dev
install:
- sudo sh -c 'echo "deb [arch=amd64] https://apt-mo.trafficmanager.net/repos/dotnet/ trusty main" > /etc/apt/sources.list.d/dotnetdev.list'
- sudo apt-key adv --keyserver apt-mo.trafficmanager.net --recv-keys 417A0893
- sudo apt-get update
- sudo apt-get --assume-yes install dotnet-dev-1.0.0-preview2-003121
solution: NModbus4.sln
script:
- dotnet restore
- cd NModbus4.UnitTests
- dotnet test
